<?xml version="1.0"?>
<package format="2">
  <name>unitree_legged_test</name>
  <version>0.0.0</version>
  <description>Python test node for unitree_legged_msgs</description>
  <maintainer email="test@example.com">test</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  
  <depend>rospy</depend>
  <depend>unitree_legged_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <!-- Other tools can request additional information be placed here -->
  </export>
</package>
